"""Pydantic schema package for IntentShelf backend contracts."""

from app.schemas.catalog import Product, User
from app.schemas.events import (
    ImpressionEvent,
    LikeEvent,
    SaveEvent,
    SearchEvent,
    Session,
    SessionEvent,
)
from app.schemas.historical import HistoricalInteraction
from app.schemas.persistence import (
    CartItemResponse,
    CartItemsResponse,
    LikeEventsResponse,
    LikeMutationRequest,
    MutationResult,
    RuntimeStateResponse,
    SaveEventsResponse,
    SaveMutationRequest,
)
from app.schemas.retrieval import (
    BlendedCandidate,
    BlendedCandidatesRequest,
    BlendedCandidatesResponse,
    CandidateExplanation,
    CandidateExplanationEvidence,
    ExplainedRerankedCandidate,
    FeedExplainRequest,
    FeedExplainResponse,
    FeedExplanationOptions,
    FeedRerankRequest,
    FeedRerankResponse,
    RankingStrategiesResponse,
    RankingStrategyDefinition,
    RankingStrategyResolution,
    RankingStrategySummary,
    RerankedCandidate,
    SessionRecommendation,
    SessionRecommendationsRequest,
    SessionRecommendationsResponse,
    SimilarProduct,
    SimilarProductsResponse,
)

__all__ = [
    "HistoricalInteraction",
    "ImpressionEvent",
    "LikeEvent",
    "BlendedCandidate",
    "BlendedCandidatesRequest",
    "BlendedCandidatesResponse",
    "CandidateExplanation",
    "CandidateExplanationEvidence",
    "ExplainedRerankedCandidate",
    "FeedExplainRequest",
    "FeedExplainResponse",
    "FeedExplanationOptions",
    "FeedRerankRequest",
    "Product",
    "FeedRerankResponse",
    "RankingStrategiesResponse",
    "RankingStrategyDefinition",
    "RankingStrategyResolution",
    "RankingStrategySummary",
    "CartItemResponse",
    "CartItemsResponse",
    "LikeEventsResponse",
    "LikeMutationRequest",
    "MutationResult",
    "RerankedCandidate",
    "RuntimeStateResponse",
    "SaveEvent",
    "SaveEventsResponse",
    "SaveMutationRequest",
    "SearchEvent",
    "Session",
    "SessionEvent",
    "SessionRecommendation",
    "SessionRecommendationsRequest",
    "SessionRecommendationsResponse",
    "SimilarProduct",
    "SimilarProductsResponse",
    "User",
]
