from datetime import datetime
from typing import Any, Literal

from pydantic import Field

from app.schemas.common import (
    IntentShelfSchema,
    SessionEventType,
    SurfaceName,
    build_prefixed_id,
    utc_now,
)


class RuntimeEvent(IntentShelfSchema):
    """
    Base class for events generated by the IntentShelf app itself.

    These runtime events are distinct from historical H&M purchases because
    they capture what the app showed or what a user did inside the app.
    """

    event_id: str = Field(default_factory=lambda: build_prefixed_id("evt"))
    event_timestamp: datetime = Field(default_factory=utc_now)
    source: Literal["intentshelf_app"] = "intentshelf_app"


class Session(IntentShelfSchema):
    """One browsing session inside the IntentShelf app."""

    session_id: str = Field(default_factory=lambda: build_prefixed_id("sess"))
    user_id: str | None = Field(
        default=None,
        description="Optional so future anonymous browsing sessions can still be logged.",
    )
    session_start: datetime = Field(default_factory=utc_now)
    session_end: datetime | None = None
    entry_surface: SurfaceName | None = None
    source: Literal["intentshelf_app"] = "intentshelf_app"


class SessionScopedEvent(RuntimeEvent):
    """Shared shape for events tied to one app session."""

    session_id: str = Field(..., min_length=1)
    user_id: str | None = None


class ProductContextEvent(IntentShelfSchema):
    """Optional product snapshot fields stored with likes and saves."""

    product_name: str | None = None
    product_type_name: str | None = None
    product_group_name: str | None = None
    colour_group_name: str | None = None
    department_name: str | None = None
    image_path: str | None = None
    explanation: dict[str, Any] | None = None
    contributing_sources: list[str] = Field(default_factory=list)
    discovery_source: str | None = None
    search_query: str | None = None


class LikeEvent(SessionScopedEvent, ProductContextEvent):
    """Represents a user explicitly liking a product."""

    event_id: str = Field(default_factory=lambda: build_prefixed_id("like"))
    session_id: str | None = None
    product_id: str = Field(..., min_length=1)


class SaveEvent(SessionScopedEvent, ProductContextEvent):
    """Represents a user saving or bookmarking a product for later."""

    event_id: str = Field(default_factory=lambda: build_prefixed_id("save"))
    session_id: str | None = None
    product_id: str = Field(..., min_length=1)


class SessionEvent(SessionScopedEvent):
    """
    Fine-grained within-session behavior such as view, click, or detail open.

    The optional source_candidate_type field is a future hook for candidate
    source tracing once multiple retrieval systems exist.
    """

    event_id: str = Field(default_factory=lambda: build_prefixed_id("sevt"))
    event_type: SessionEventType
    source_surface: SurfaceName
    product_id: str | None = None
    rank_position: int | None = Field(default=None, ge=1)
    source_candidate_type: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class SearchEvent(SessionScopedEvent):
    """Represents a search query issued during a session."""

    event_id: str = Field(default_factory=lambda: build_prefixed_id("search"))
    query_text: str = Field(..., min_length=1)
    num_results: int | None = Field(default=None, ge=0)
    strategy_used: str | None = None
    request_id: str | None = None


class ImpressionEvent(SessionScopedEvent):
    """
    Records that a product was shown to the user.

    Impression logging is important later for ranking analysis because it lets
    us compare what the system showed against what the user clicked, saved, or
    ignored.
    """

    event_id: str = Field(default_factory=lambda: build_prefixed_id("impr"))
    session_id: str | None = None
    product_id: str = Field(..., min_length=1)
    surface: SurfaceName
    rank_position: int = Field(..., ge=1)
    ranking_strategy: str = Field(
        ...,
        min_length=1,
        description="Human-readable strategy label for future experiment analysis.",
    )
    primary_source: str | None = Field(
        default=None,
        description="Simple source label such as collaborative, content, or search.",
    )
    candidate_sources: list[str] = Field(default_factory=list)
    explanation_reason: str | None = Field(
        default=None,
        description="Optional user-facing explanation label saved with the impression.",
    )
    request_id: str | None = None
